sentences = [
    "Ochrona środowiska jest bardzo ważna we współczesnym świecie",
    "Powinniśmy zrezygnować z zanieczyszczających środowisko źródeł energii",
    "Regulacje środowiskowe są potrzebne",
    "Państwo powinno przeciwdziałać globalnemu ociepleniu",
    "Człowiek przykłada obecnie zbyt dużą wagę do ochrony zwierząt hodowlanych",
    "Segregacja śmieci powinna być obowiązkiem",
    "Należy zmniejszyć produkcje mięsa",
    "Złym jest samo istnienie państwa",
    "W trakcie kryzysu autorytaryzm jest lepszy od demokracji",
    "Czystość rasowa jest lepsza od mieszania się ras",
    "Aborcja powinna być legalna na życzenie",
    "Państwo powinno poczynić dodatkowe starania w celu ograniczenia dostępu do pornografii nieletnim",
    "Ustrój państwa powinien być oparty na zasadach szerokiej decentralizacji",
    "Prawo Pracy powinno zostać zniesione lub mocno ograniczone",
    "Związki partnerskie pomiędzy osobami tej samej płci powinny być legalne",
    "Symbole narodowe mają dużą wartość",
    "Wychowywanie w duchu tradycyjnych wartości jest kluczowe dla istnienia i rozwoju społeczeństwa",
    "Osoby o innej religii niż moja stwarzają zagrożenie dla porządku publicznego",
    "Władza musi być zakorzeniona w tradycji",
    "Rola państwa powinna zostać maksymalnie ograniczona",
    "Obywatele powinni mieć łatwy dostęp do broni",
    "Popieram zagwarantowanie obowiązkowej reprezentacji pracowników w zarządach prywatnych firm",
    "Zawsze popierałbym moje państwo, bez względu na to czy postępuje właściwie",
    "Bycie dumnym ze swojego pochodzenia jest nieuzasadnione",
    "Kościół nie powinien mieć większego wpływu na państwo niż inne organizacje",
    "W szkołach publicznych powinno zakazać się nauczania religii",
    "Państwo powinno tworzyć program nauczania według którego muszą uczyć wszystkie szkoły",
    "Służba wojskowa powinna być obowiązkowa",
    "Nieheteroseksualizm jest czymś co należy zwalczać/leczyć",
    "Popieram depenalizację miękkich narkotyków",
    "Rząd w pewnych sytuacjach powinien móc ograniczać wolność obywateli (np. w celu ochrony przed terroryzmem)",
    "Rząd powinien promować patriotyzm oraz kulturę mojego narodu",
    "Silna armia jest potrzebna",
    "Należy dążyć do utworzenia rządu światowego",
    "Wolność człowieka kończy się tam gdzie zaczyna się wolność drugiego",
    "Silna władza jest potrzebna by utrzymać porządek w kraju",
    "Obywatelstwo powinno być przyznawane jedynie obcokrajowcom znającym historię narodu",
    "Społeczeństwo nie powinno dążyć do zacierania różnic między płciami, lecz większego eksponowania cech męskich i żeńskich",
    "Patenty nie powinny istnieć",
    "Państwo powinno przeciwdziałać prywatnym monopolom",
    "Małżeństwa powinny zostać zniesione",
    "Postęp techniczny jest pożądany, nawet jeżeli prowadzi do gruntownych zmian społecznych, lub środowiskowych",
    "Defilady wojskowe są potrzebne",
    "Władza powinna skupiać się w rękach jednej partii",
    "Inwigilacja przez rząd jest pożądana",
    "Eutanazja powinna być legalna",
    "Religia to opium ludu",
    "Pokojowa współpraca międzynarodowa jest o wiele bardziej opłacalna niż sankcje i przemoc",
    "Interes mojego kraju jest ważniejszy od interesu innych krajów",
    "Ostracyzm społeczeństwa jest bardziej efektywny niż przymus państwowy",
    "Popieram tradycyjny model rodziny",
    "Monarchia to dobry ustrój polityczny i go popieram",
    "Popieram organizacje międzynarodowe takie jak Unia Europejska",
    "Mój kraj powinien dążyć do zdobycia terenów, które kiedyś posiadał",
    "Obowiązkiem każdego obywatela jest obrona ojczyzny",
    "Resocjalizacja jest ważniejsza niż kara",
    "Popieram akcje afirmacyjne",
    "Popieram pełną równość płci na wszystkich płaszczyznach życia",
    "Jestem dumny z historii mojego kraju",
    "Laicyzacja kultury jest zjawiskiem pożądanym",
    "Jeśli mamy przyjąć imigrantów, muszą zostać poddani skrupulatnej selekcji",
    "Przywrócenie kary śmierci to dobry pomysł",
    "Opresyjność władzy jest wystarczającym powodem by wszcząć wobec niej bunt",
    "Państwo nie powinno posiadać armii",
    "In vitro powinno być refundowane",
    "Wszystko w państwie, nic poza państwem, nic przeciw państwu",
    "Władzy totalnej, bądź totalitarnej, nie należy się wystrzegać",
    "Wiek zgody powinien zostać obniżony, bądź zniesiony",
    "Rozwiązłość seksualna jest niemoralna",
    "Lepszym partnerem jest zawsze osoba tej samej narodowości",
    "Państwo powinno aktywnie wspierać zatrudnienie bezrobotnych",
    "Rynek powinien być regulowany w celu ochrony konsumentów",
    "Wolność negatywna jest ważniejsza od równości",
    "Państwo powinno zapewniać osobom w skrajnej biedzie minimum wymagane do przetrwania",
    "Upaństwawianie kluczowych sektorów gospodarki jest korzystne",
    "Wolny rynek korzystnie wpływa na gospodarkę",
    "Waluta z parytetem złota jest lepsza od pieniądza fiducjarnego",
    "Rząd powinien zwalczać nierówności w płacach kobiet i mężczyzn",
    "Rząd powinien ograniczyć import z innych krajów, aby promować producentów krajowych",
    "Podatki to kradzież i docelowo nie powinny istnieć",
    "Podatki powinny być progresywne",
    "Walka o równość klas społecznych jest priorytetem",
    "Emerytura jest kwestią indywidualnego planowania, nie powinna być organizowana przez państwo",
    "Prywatna działalność charytatywna powinna być głównym kanałem pomocy ubogim i potrzebującym",
    "Licencje, zezwolenia i związki zawodowe są szkodliwe",
    "Związki zawodowe powinny podlegać przepisom obowiązującym każde inne stowarzyszenie",
    "Rząd powinien gwarantować powszechny i darmowy dostęp do opieki zdrowotnej finansowanej z budżetu państwa",
    "Bank centralny musi być w pełni niezależny od władzy wykonawczej",
    "Silniejsze podmioty gospodarcze, mające dużą przewagę konkurencyjną, powinny podlegać surowym regulacjom",
    "Biedni ludzie są biedni w wyniku swoich złych decyzji",
    "Badania naukowe powinny być głównie finansowane przez państwo",
    "Prawo do dziedziczenia powinno zostać zlikwidowane",
    "Własność prywatna powinna zostać zniesiona",
    "Nie jest dopuszczalne ograniczenie własności prywatnej w jakichkolwiek przypadkach",
    "Państwo powinno zajmować się jedynie obroną praw jednostkowych (wojsko, policja, sądy)",
    "Państwo powinno zapewniać najbiedniejszym mieszkanie i godne warunki życia",
    "Władze powinny zwalczać recesję i wysokie bezrobocie, nawet kosztem wysokiej inflacji",
    "Podwyższenie kwoty wolnej od podatku jest lepszym rozwiązaniem niż wspieranie najbiedniejszych zasiłkami socjalnymi",
    "Państwo powinno organizować budowę strategicznych obiektów",
    "Od każdego według możliwości, każdemu według potrzeb"
]
